### ISSUE TITLE
Blackbox test Shopify App

### ISSUE THREAD

**Issue by sfaria27** [tiki/tiki-shopify#106]

**Comment by ricardobrg** [comment]
If a product discount has an "Applies to" filter, it breaks TIKI sqlite database when accepted:

```
Uncaught SqliteException(11): while executing, database disk image is malformed, database disk image is malformed (code 11)
  Causing statement:     CREATE TABLE IF NOT EXISTS txn (
      id BLOB PRIMARY KEY NOT NULL,
      merkel_proof BLOB,
      version INTEGER NOT NULL,
      address BLOB NOT NULL,
      contents BLOB NOT NULL,
      asset_ref TEXT NOT NULL,
      block_id BLOB, 
      timestamp INTEGER NOT NULL,
      user_signature BlOB NOT NULL,
      app_signature BlOB,
      FOREIGN KEY(block_id) 
        REFERENCES block(id)
     ); 
    , parameters: 
    at Object.d (https://unpkg.com/@mytiki/tiki-sdk-js@2.1.4/dist/index.js:1:12959)
    at Object.A5 (https://unpkg.com/@mytiki/tiki-sdk-js@2.1.4/dist/index.js:1:153256)
    at rc.c0 (https://unpkg.com/@mytiki/tiki-sdk-js@2.1.4/dist/index.js:1:519417)
    at rc.cz (https://unpkg.com/@mytiki/tiki-sdk-js@2.1.4/dist/index.js:1:519557)
    at https://unpkg.com/@mytiki/tiki-sdk-js@2.1.4/dist/index.js:1:143764
    at G.a (https://unpkg.com/@mytiki/tiki-sdk-js@2.1.4/dist/index.js:1:42343)
    at zE.$2 (https://unpkg.com/@mytiki/tiki-sdk-js@2.1.4/dist/index.js:1:188691)
    at zp.$1 (https://unpkg.com/@mytiki/tiki-sdk-js@2.1.4/dist/index.js:1:188587)
    at z2.v4 (https://unpkg.com/@mytiki/tiki-sdk-js@2.1.4/dist/index.js:1:200965)
    at z2.jk (https://unpkg.com/@mytiki/tiki-sdk-js@2.1.4/dist/index.js:1:201017)
    ```

**Comment by ricardobrg** [comment]
The discount details are not showing correct values.

Steps to reproduce
- create an discount
- open the discount in the menu
- check the values are not matching

**Comment by ricardobrg** [comment]
The discount/license accepted cookies should be saved faster. If the user accepts the offer and navigates faster to another page, the banner will keep showing because the decision wasn't saved.

This might be the expected behaviour, since we need to make sure that the user choice was correctly saved. To be defined the best approach.

**Comment by ricardobrg** [comment]
Banner should not show in contact screen and should show in catalog screen.

**Comment by ricardobrg** [comment]
Add an option to cap the number of itens in product discount

**Comment by ricardobrg** [comment]
fix the sizing of the banner for screens below 1024px. Related to https://github.com/tiki/tiki-sdk-js/issues/135

**Comment by sfaria27** [comment]
Minimum order discount should be ≥ not >

**Comment by ricardobrg** [comment]
If all combinations boxes are selected just shipping is registered

Possible causes:
- the form is not sending the correct value
- our backend is not saving correclty this option
- Shopify just allows product discounts combined with shipping discounts and the Combinations UI should be updated (most likely)

**Comment by ricardobrg** [comment]
Above comments fixed in 
https://github.com/tiki/apps-shopify-extensions/issues/117
https://github.com/tiki/apps-shopify-extensions/issues/118
[fix: banner should show in all screens](https://github.com/tiki/apps-shopify-extensions/pull/119/commits/4ab0f94a1d286d1b03641529f8f2f93c97708ddc) [4ab0f94](https://github.com/tiki/apps-shopify-extensions/pull/119/commits/4ab0f94a1d286d1b03641529f8f2f93c97708ddc)
[fix: order min value/qty >=](https://github.com/tiki/apps-shopify-extensions/pull/119/commits/34857c9e2fa7ee878f5c5f3cdf6bab79c4315fc6) [34857c9](https://github.com/tiki/apps-shopify-extensions/pull/119/commits/34857c9e2fa7ee878f5c5f3cdf6bab79c4315fc6)

Working on #116

**Comment by ricardobrg** [comment]
Blocked by https://github.com/tiki/publish-sdk-js/issues/108
